### ISSUE TITLE
Feature Request: Add LiteLLM Proxy Integration to OpenWebUI

### ISSUE THREAD

**Issue by usrbinkat** [usrbinkat/obelisk#14]
## Overview
This issue proposes adding native LiteLLM proxy integration to OpenWebUI. LiteLLM would serve as a middleware layer that standardizes access to multiple LLM providers (OpenAI, Gemini, Mistral, etc.), provides API key management, tracks usage, and enables budget controls.

## Benefits
- **Access to 100+ LLM providers** through a single, standardized interface
- **Centralized API key management** and security
- **Usage tracking and budget controls** to prevent unexpected costs
- **Request/response logging** to supported destinations (Langfuse, S3, etc.)
- **Team-based access controls** for enterprise environments

### Components Needed
1. **Docker Compose Integration**:
   - Add LiteLLM proxy service
   - Add PostgreSQL DB for LiteLLM data storage
   - Configure networking between OpenWebUI and LiteLLM

2. **Configuration Updates**:
   - Environment variable support for LiteLLM connection
   - Default litellm-config.yaml template
   - Documentation for custom setups

3. **UI Enhancements**:
   - First-time setup wizard for LiteLLM configuration
   - Model selection integration with LiteLLM-provided models
   - Usage analytics display

### Technical Considerations
- Ensure proper rendering of "thinking" content using `<think></think>` tags
- Implement proper error handling for LiteLLM connection issues
- Ensure compatibility with existing OpenWebUI features like RAG
- Add Apache Tika integration for document processing

### Proposed Docker Compose Changes
A first draft of the necessary docker-compose.yaml changes has been created and tested locally. The key additions would be:

```yaml
# LiteLLM Proxy
litellm:
  container_name: litellm
  image: ghcr.io/berriai/litellm:main-latest
  ports:
    - "4000:4000"
  volumes:
    - ./litellm-config.yaml:/app/config.yaml
  environment:
    - LITELLM_MASTER_KEY=${LITELLM_MASTER_KEY:-sk-1234}
    - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@${POSTGRES_HOST:-litellm_db}:${POSTGRES_PORT:-5432}/${POSTGRES_DATABASE:-postgres}
    - STORE_MODEL_IN_DB=True
  env_file:
    - .env
  depends_on:
    - litellm_db
  networks:
    - openwebui-network

# LiteLLM Database
litellm_db:
  image: postgres:16.1
  container_name: litellm_db
  restart: always
  environment:
    - POSTGRES_USER=${POSTGRES_USER:-postgres}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    - POSTGRES_PORT=${POSTGRES_PORT:-5432}
    - POSTGRES_DATABASE=${POSTGRES_DATABASE:-postgres}
  volumes:
    - postgres_data:/var/lib/postgresql/data
  networks:
    - openwebui-network
```

### Configuration Example (litellm-config.yaml)
```yaml
# Model configuration - lists all models available through the proxy
model_list:
  # Ollama models - direct access to your local models
  - model_name: ollama/llama3
    litellm_params:
      model: ollama/llama3
      api_base: http://ollama:11434
      drop_params: true # Removes extra parameters when calling specific models

  # OpenAI models - requires API key
  - model_name: openai/gpt-4o
    litellm_params:
      model: openai/gpt-4o
      api_key: os.environ/OPENAI_API_KEY
      drop_params: true

  # Gemini models - requires API key
  - model_name: gemini/gemini-1.5-pro
    litellm_params:
      model: gemini/gemini-1.5-pro
      api_key: os.environ/GEMINI_API_KEY
      rpm: 15
      tpm: 1000000
      drop_params: true

  # Embedding model for RAG
  - model_name: gemini/text-embedding-004
    litellm_params:
      model: gemini/text-embedding-004
      api_key: os.environ/GEMINI_API_KEY
      rpm: 15
      tpm: 1000000
      drop_params: true

# General settings
general_settings:
  # Forward OpenAI Organization ID for enterprise customers
  forward_openai_org_id: true

# LiteLLM specific settings
litellm_settings:
  # Enable schema validation for requests
  enable_json_schema_validation: True
  # Enable Langfuse tracing (optional)
  # langfuse_project_id: os.environ/LANGFUSE_PROJECT_ID
  # langfuse_public_key: os.environ/LANGFUSE_PUBLIC_KEY
  # langfuse_secret_key: os.environ/LANGFUSE_SECRET_KEY
```

### Full Docker Compose Example
```yaml
version: "3.9"
services:
  # LiteLLM Proxy - Acts as middleware between OpenWebUI and various LLM providers
  litellm:
    container_name: litellm
    image: ghcr.io/berriai/litellm:main-latest
    ports:
      - "4000:4000" # LiteLLM proxy API
    volumes:
      - ./litellm-config.yaml:/app/config.yaml # Mount your config
    environment:
      - LITELLM_MASTER_KEY=${LITELLM_MASTER_KEY:-sk-1234} # Master key for admin access
      # Database connection for tracking usage, keys, etc.
      - DATABASE_URL=postgresql://${LITELLM_POSTGRES_USER:-postgres}:${LITELLM_POSTGRES_PASSWORD:-postgres}@${LITELLM_POSTGRES_HOST:-litellm_db}:${LITELLM_POSTGRES_PORT:-5432}/${LITELLM_POSTGRES_DATABASE:-postgres}
      - STORE_MODEL_IN_DB=True # allows adding models to proxy via UI
    env_file:
      - .env # For API keys to various LLM providers
    command: ["--config", "/app/config.yaml", "--port", "4000", "--num_workers", "8"]
    networks:
      - ollama-net
    depends_on:
      - litellm_db
    restart: unless-stopped

  # PostgreSQL Database for LiteLLM
  litellm_db:
    image: postgres:16.1
    container_name: litellm_db
    restart: always
    environment:
      - POSTGRES_USER=${LITELLM_POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${LITELLM_POSTGRES_PASSWORD:-postgres}
      - POSTGRES_PORT=${LITELLM_POSTGRES_PORT:-5432}
      - POSTGRES_DATABASE=${LITELLM_POSTGRES_DATABASE:-postgres}
      - POSTGRES_HOST=${LITELLM_POSTGRES_HOST:-litellm_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ollama-net

  # Tika service for document processing in OpenWebUI
  tika:
    image: apache/tika:latest-full
    container_name: tika
    ports:
      - "9998:9998"
    restart: unless-stopped
    networks:
      - ollama-net

  # OpenWebUI - Front-end interface
  open-webui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:main
    environment:
      - LOG_LEVEL=debug
      # Connect to LiteLLM proxy instead of directly to obelisk-rag
      - OPENAI_API_BASE_URL=http://litellm:4000
      - OPENAI_API_KEY=${LITELLM_VIRTUAL_KEY:-sk-1234} # Use a LiteLLM virtual key
      # For RAG capability (uncomment if needed)
      - ENABLE_RAG=True
      - RAG_EMBEDDING_ENGINE=openai
      - RAG_OPENAI_API_BASE_URL=http://litellm:4000
      - RAG_OPENAI_API_KEY=${LITELLM_VIRTUAL_KEY:-sk-1234}
      - RAG_EMBEDDING_MODEL=gemini/text-embedding-004
      - TIKA_SERVER_URL=http://tika:9998
      - CONTENT_EXTRACTION_ENGINE=tika
    volumes:
      - data:/data
      - models:/models
      - open-webui:/config
    ports:
      - "8080:8080"
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "2"
    depends_on:
      - litellm
      - tika
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - ollama-net
    restart: unless-stopped
  
  # Ollama service for local model hosting
  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - CUDA_VISIBLE_DEVICES=0
      - LOG_LEVEL=debug
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: all
    volumes:
      - ollama:/root/.ollama
      - models:/models
    ports:
      - "11434:11434"
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "2"
    networks:
      - ollama-net
    restart: unless-stopped

volumes:
  data:
  models:
  ollama:
  open-webui:
  postgres_data:

networks:
  ollama-net:
    driver: bridge
```

### Documentation Requirements
1. Setup guide for basic integration
2. Advanced configuration options
3. User management and team creation workflow
4. Troubleshooting common issues

### Testing Plan
- Test integration with various LLM providers
- Verify API key management functionality
- Test performance and reliability under load
- Verify compatibility with existing OpenWebUI features

### References
- [LiteLLM Documentation](https://docs.litellm.ai/docs/)
- [OpenWebUI Documentation](https://docs.openwebui.com/)
- [Running LiteLLM and OpenWebUI on Windows Localhost](https://www.tanyongsheng.com/note/running-litellm-and-openwebui-on-windows-localhost-a-comprehensive-guide/)
