### ISSUE TITLE
feat(docker): Add Milvus vector database MVP integration to docker-compose

### ISSUE THREAD

**Issue by usrbinkat** [usrbinkat/obelisk#16]
## Overview
Integrate Milvus vector database into the Obelisk stack by adding the necessary containers to docker-compose.yml and connecting it to OpenWebUI for RAG capabilities.

## Goals
- Add Milvus standalone container to docker-compose.yml
- Add required supporting services (etcd, minio)
- Configure the services with appropriate volumes and settings
- Update the OpenWebUI integration to use Milvus as the vector database option

## Tasks
- [x] Add etcd service to docker-compose.yml
- [x] Add minio service to docker-compose.yml
- [x] Add milvus standalone service to docker-compose.yml
- [x] Configure appropriate volume mappings for persistence
- [x] Set necessary environment variables for Milvus configuration
- [x] Update OpenWebUI configuration to connect to Milvus
- [x] Test the integration with basic vector operations
- [x] Update documentation to reflect the Milvus integration

## Implementation Details
Based on the Milvus example docker-compose.yml:
```yaml
services:
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.18
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ./volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://etcd:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9001:9001"
      - "9000:9000"
    volumes:
      - ./volumes/minio:/minio_data
    command: minio server /minio_data --console-address ":9001"

  milvus:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.5.10
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ./volumes/milvus:/var/lib/milvus
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "etcd"
      - "minio"
```

The OpenWebUI environment variables required for Milvus integration:
```
RETRIEVAL_ENABLED=true
RETRIEVAL_VECTOR_STORE=milvus
MILVUS_URI=http://milvus:19530
MILVUS_HOST=milvus
MILVUS_PORT=19530
```

## Implementation Status
- ✅ **Complete:** All services have been added to docker-compose.yml
- ✅ **Complete:** All necessary configuration has been implemented
- ✅ **Complete:** Testing verifies the Milvus integration works
- ✅ **Complete:** Documentation added to the vault directory

## References
- [Milvus Docker QuickStart](https://milvus.io/docs/install_standalone-docker.md)
- [Vector database environment variables in OpenWebUI](https://docs.openwebui.com/getting-started/env-configuration/#vector-database)
