### ISSUE TITLE
Race Condition Between LiteLLM Container and Init-Service Blocks Initialization Process

### ISSUE THREAD

**Issue by usrbinkat** [usrbinkat/obelisk#32]
## Issue Summary
There is a critical race condition in the container initialization sequence that prevents the integration tests from completing successfully. The LiteLLM container requires a configuration file (`/app/config/litellm_config.yaml`) to start properly, but this file is only created by the `init-service` container. However, the `init-service` depends on LiteLLM being available before it can complete its tasks, creating a circular dependency.

## Reproduction Steps
1. Clean the environment with `task clean-all-purge`
2. Start the services in the documented order:
   ```bash
   docker-compose up -d etcd minio milvus
   docker-compose up -d ollama
   docker-compose up -d litellm_db litellm
   docker-compose up init-service
   ```
3. Observe that the `init-service` hangs at the "Waiting for LiteLLM API to be available" step
4. Check LiteLLM logs to see it repeatedly crashing with `Exception: Config file not found: /app/config/litellm_config.yaml`

## Root Cause Analysis
The root cause is a startup order and dependency issue:

1. According to `docker-compose.yaml`, LiteLLM is configured with `command: ["--port", "4000", "--config", "/app/config/litellm_config.yaml"]`, which requires the config file to exist
2. The volume `config:/app/config:rw` is shared between `litellm` and `init-service`
3. In `docker/init-scripts/configure-services.sh`, the function `configure_litellm()` is responsible for creating the config file at `/app/config/litellm_config.yaml`
4. However, this function is only executed when the init-service runs
5. The init-service, as shown in `docker/init-scripts/generate-tokens.sh`, waits for LiteLLM to be available before proceeding
6. LiteLLM cannot start without the config file, and the config file cannot be created until the init-service runs, resulting in a deadlock

## Impact
This issue blocks the automated testing process and prevents initialization of the OpenAI integration test. It also affects any deployment that follows the recommended initialization sequence in the documentation.

### Affected Components
- LiteLLM container
- init-service container
- Configuration management process

### Relevant Code
In `docker-compose.yaml`:
```yaml
litellm:
  command: ["--port", "4000", "--config", "/app/config/litellm_config.yaml"]
  volumes:
    - config:/app/config:rw
```

In `docker/init-scripts/generate-tokens.sh`:
```bash
# Wait for LiteLLM service to be available
MAX_RETRIES=30
RETRY_INTERVAL=5
retries=0

while [ $retries -lt $MAX_RETRIES ]; do
  if curl -s "$LITELLM_API_URL/health" > /dev/null 2>&1; then
    echo "LiteLLM API is available"
    break
  fi
  
  echo "Waiting for LiteLLM API to be available... (retry $retries of $MAX_RETRIES)"
  sleep $RETRY_INTERVAL
  retries=$((retries + 1))
done
```

In `docker/init-scripts/configure-services.sh`:
```bash
function configure_litellm() {
  echo "Configuring LiteLLM service..."
  # ... configuration logic ...
  cat > "$CONFIG_DIR/litellm_config.yaml" << EOF
  # LiteLLM Configuration
  # ... configuration content ...
EOF
}
```

LiteLLM container logs show:
```
Exception: Config file not found: /app/config/litellm_config.yaml
```

## Proposed Solution

There are several potential solutions to this issue:

1. **Minimal Bootstrap Config File**:
   Create a minimal default config file in the LiteLLM container image that can be overridden later by init-service. This allows LiteLLM to start without the full configuration.

2. **Two-Phase Initialization**:
   Modify init-service to run in two phases:
   - Phase 1: Create minimal configuration files
   - Phase 2: Wait for services to be available and perform full configuration

3. **Environment Variables Instead of Config File**:
   Modify LiteLLM to use environment variables for critical configuration instead of requiring a config file to start.

4. **Initialization Order Change**:
   Update the startup sequence documentation to create the config directory and a minimal config file before starting LiteLLM.

### Selected Solution: Environment Variables (Option #3)

We've implemented Solution #3, which uses environment variables for bootstrapping LiteLLM. This avoids the circular dependency by allowing LiteLLM to start with minimal configuration, while still enabling the init-service to enhance the configuration using the API.

Key changes:
1. Removed the `--config` flag from LiteLLM command in docker-compose.yaml
2. Added environment variables for basic model configuration
3. Enhanced the initialization scripts to handle authenticated API connections
4. Added mechanisms to handle delayed registration and be more resilient to timing issues

This solution resolved the race condition while requiring minimal changes to the codebase and maintaining compatibility with existing configurations.

**Comment by usrbinkat** [comment]
## Environment Variables Solution to Break the Circular Dependency

After analyzing the issue further, I've identified the most robust solution that doesn't require modifying the container image or adding local filesystem dependencies. LiteLLM supports bootstrapping via environment variables instead of requiring a config file, which solves our initialization race condition.

### Proposed Implementation

1. **Update docker-compose.yaml** to add minimal model configuration directly via environment variables:

```yaml
litellm:
  container_name: litellm
  image: ghcr.io/berriai/litellm:main-latest
  ports:
    - "4000:4000"
  environment:
    # Authentication keys
    - LITELLM_MASTER_KEY=${LITELLM_API_TOKEN:-sk-1234}
    - LITELLM_ADMIN_PASSWORD=${LITELLM_ADMIN_PASSWORD:-admin}
    - DATABASE_URL=postgresql://postgres:postgres@litellm_db:5432/postgres
    
    # Base Ollama config - this bootstraps the system with minimal model config
    - MODEL_NAME_1=llama3
    - MODEL_1=ollama/llama3
    - MODEL_API_BASE_1=http://ollama:11434
    
    # Base embedding model config
    - MODEL_NAME_2=mxbai-embed-large
    - MODEL_2=ollama/mxbai-embed-large
    - MODEL_API_BASE_2=http://ollama:11434
    
    # Existing OpenAI config
    - OPENAI_API_KEY=${OPENAI_API_KEY:-}
    - OPENAI_ORG_ID=${OPENAI_ORG_ID:-}
    - USE_OPENAI=${USE_OPENAI:-false}
    - OPENAI_EMBEDDING_MODEL=${OPENAI_EMBEDDING_MODEL:-text-embedding-3-large}
    - OPENAI_COMPLETION_MODEL=${OPENAI_COMPLETION_MODEL:-gpt-4o}
    
    # Tell LiteLLM to save registered models to the DB for persistence
    - STORE_MODEL_IN_DB=true
    
    # Existing config
    - LITELLM_MODEL_CONFIG=/app/config/litellm_config.yaml
    - LITELLM_TOKEN_UID=obelisk-api-token
  volumes:
    - tokens:/app/tokens:ro
    - config:/app/config:rw
  command: ["--port", "4000"]  # Remove --config flag to allow bootstrapping with environment vars
  networks:
    - ollama-net
  depends_on:
    - litellm_db
    - ollama
  restart: unless-stopped
  logging:
    driver: json-file
    options:
      max-size: "5m"
      max-file: "2"
```

2. **Modify configure-services.sh** to use API-based model registration:

The script should continue to create the full config file, but instead of expecting LiteLLM to restart and read it, we'll register the models dynamically via LiteLLM's API endpoints. This way, the service is already running when we enhance its configuration.

Update `docker/init-scripts/configure-services.sh` to register models via API after creating the config file:

```bash
function configure_litellm() {
  echo "Configuring LiteLLM service..."
  
  # Create config file as before
  cat > "$CONFIG_DIR/litellm_config.yaml" << EOF
  # LiteLLM Configuration
  # Generated at: $(date)
  
  model_list:
    # ... config content ...
EOF

  echo "LiteLLM configuration file created"
  
  # Now register models via API for immediate availability
  # Wait for LiteLLM API to be available
  MAX_RETRIES=30
  RETRY_INTERVAL=5
  retries=0
  
  while [ $retries -lt $MAX_RETRIES ]; do
    if curl -s "$LITELLM_API_URL/health" > /dev/null 2>&1; then
      echo "LiteLLM API is available for model registration"
      break
    fi
    
    echo "Waiting for LiteLLM API to be available... (retry $retries of $MAX_RETRIES)"
    sleep $RETRY_INTERVAL
    retries=$((retries + 1))
  done
  
  if [ $retries -eq $MAX_RETRIES ]; then
    echo "Error: LiteLLM API did not become available for model registration"
    return 1
  fi
  
  # Register additional models through the API
  # ... model registration logic ...
  
  echo "LiteLLM configuration complete - models registered via API"
}
```

### Benefits of This Approach

1. **No Circular Dependency**: LiteLLM starts with minimal configuration from environment variables
2. **No Local File Dependencies**: No need to modify the container or add local filesystem mounts
3. **Graceful Enhancement**: The basic service starts first, then gets enhanced via its own API
4. **Resilient to Restarts**: If LiteLLM restarts, it will still have minimal config from environment variables
5. **Consistent with Docs**: LiteLLM documentation explicitly supports this environment variable approach

### Testing Notes

This approach keeps the testing sequence intact:
1. Start infrastructure services (etcd, minio, milvus)
2. Start AI services (ollama, litellm_db, litellm)
3. Run initialization service, which enhances the already-running LiteLLM configuration
4. Start application services (obelisk-rag, open-webui, obelisk)

We can test with or without OpenAI API keys to validate the fallback behavior works correctly with both the bootstrap and enhanced configuration.

In our testing workflows, this change is transparent - the initialization sequence remains the same but without the race condition.
