### ISSUE TITLE
Feature: Embedding Generation Microservice

### ISSUE THREAD

**Issue by usrbinkat** [usrbinkat/obelisk#34]
## Overview

Create a dedicated Embedding Generation microservice as part of the new microservices architecture for Obelisk's RAG system. This service will be responsible for efficiently generating vector embeddings from document chunks while supporting multiple embedding models and providers.

## Current Implementation Limitations

The current embedding functionality in `obelisk/rag/embedding.py` has several limitations:

- Tightly coupled with the main RAG service
- Limited to sequential processing of embedding requests
- No caching mechanisms for frequent embedding requests
- Basic provider switching without sophisticated fallback
- Limited scalability for high-volume embedding generation
- No batching optimizations for performance
- No direct scaling capabilities for embedding-intensive workloads

### Core Functionality

1. **Multi-Provider Support**
   - Support for both OpenAI and Ollama embedding models
   - Seamless fallback between providers when one is unavailable
   - Configurable default provider with override capabilities
   - Connection pooling for provider APIs
   - Model consistency validation across providers

2. **Embedding Generation**
   - Generate embeddings for document chunks
   - Support query embedding generation
   - Normalize embeddings for consistent similarity search
   - Implement dimension reduction options for storage efficiency
   - Support different embedding models with configuration

3. **Performance Optimization**
   - Implement batch processing of embedding requests
   - Support parallel processing of multiple documents
   - Optimize request throttling based on API limits
   - Implement connection pooling for improved throughput
   - Provide streaming capabilities for large document sets

4. **Caching System**
   - Implement robust caching of embeddings by content hash
   - Support time-based cache invalidation
   - Implement LRU cache eviction policies
   - Track cache hit/miss statistics
   - Support persistent caching to disk

5. **Message Queue Integration**
   - Consume document chunk events from message queue
   - Publish completed embedding events
   - Implement error handling and retry logic
   - Support dead letter queues for failed embeddings
   - Ensure exactly-once processing guarantees

6. **Monitoring and Metrics**
   - Track embedding generation times
   - Monitor API rate limits and usage
   - Record provider availability and failures
   - Expose prometheus-compatible metrics
   - Implement detailed logging for debugging

### Technical Architecture

**Service Components:**
- Provider Manager: Handles different embedding providers
- Embedding Generator: Core embedding generation logic
- Batch Processor: Optimizes embedding requests into batches
- Cache Manager: Handles embedding caching and retrieval
- Message Consumer: Processes incoming document chunk events
- Message Publisher: Publishes completed embedding events
- Metrics Collector: Gathers and exposes service metrics

**API Endpoints:**
- `/embed/text` - Generate embeddings for text
- `/embed/document` - Generate embeddings for document chunks
- `/embed/query` - Generate embeddings for search queries
- `/stats` - Get embedding service statistics
- `/health` - Service health check endpoint
- `/config` - Manage service configuration

**Performance Architecture:**
- Worker Pool: Pool of workers for parallel embedding generation
- Request Queue: Internal queue for embedding requests
- Rate Limiter: Controls API request rates
- Cache Layer: Efficient caching of generated embeddings
- Batch Collector: Groups requests for batch processing

**Message Format:**
```json
{
  "event_type": "embedding_request",
  "chunk_id": "doc1_chunk1",
  "document_id": "vault/path/to/document.md",
  "chunk_hash": "sha256:789xyz...",
  "content": "Document content to embed...",
  "metadata": {
    "source": "vault/path/to/document.md",
    "chunk_index": 1,
    "total_chunks": 5
  },
  "provider_preference": "openai",
  "model_preference": "text-embedding-3-large",
  "timestamp": "2025-04-23T22:30:00Z"
}
```

**Response Format:**
```json
{
  "event_type": "embedding_complete",
  "chunk_id": "doc1_chunk1",
  "document_id": "vault/path/to/document.md",
  "chunk_hash": "sha256:789xyz...",
  "embedding_id": "emb_12345",
  "embedding_provider": "openai",
  "embedding_model": "text-embedding-3-large",
  "embedding_dimensions": 3072,
  "embedding": [0.123, 0.456, ...],
  "processing_time_ms": 150,
  "timestamp": "2025-04-23T22:30:01Z"
}
```

## Integration Points

1. **Document Reconciliation Service**
   - Receive document chunk events from the Document Reconciliation service
   - Process chunks and generate embeddings
   - Send completion events back to Document Reconciliation service
   - Support document revision with embedding updates

2. **Vector Database Service**
   - Send generated embeddings to Vector Database service
   - Include proper metadata for storage
   - Support bulk insert operations for efficiency
   - Implement proper error handling for storage failures

3. **LiteLLM Integration**
   - Leverage LiteLLM for model routing and fallback
   - Use LiteLLM's token management
   - Implement proper authentication with LiteLLM
   - Support dynamic model configuration via LiteLLM

4. **Direct Provider Integration**
   - Connect directly to OpenAI API when available
   - Connect directly to Ollama for local embedding
   - Implement proper fallback between providers
   - Support dynamic provider switching

## Performance Considerations

1. **Scalability**
   - Design for horizontal scaling based on embedding load
   - Support stateless operation for easy scaling
   - Implement worker pool for parallel processing
   - Define clear resource requirements for different workloads

2. **Throughput Optimization**
   - Batch similar requests for improved throughput
   - Implement priority queues for urgent embedding requests
   - Support adaptive batch sizing based on load
   - Optimize connection management for persistent connections

3. **Cost Management (for OpenAI)**
   - Implement token counting for cost estimation
   - Track usage metrics by model and operation
   - Support cost-based routing decisions
   - Implement rate limiting to prevent accidental overuse

4. **Caching Strategy**
   - Define cache key generation based on content hash
   - Implement tiered caching (memory, disk, distributed)
   - Support configurable cache TTL and eviction policies
   - Track and expose cache effectiveness metrics

### Phase 1: Core Embedding Service
- Implement basic embedding service with provider support
- Add simple API endpoints for embedding generation
- Support both OpenAI and Ollama providers
- Implement basic configuration management

### Phase 2: Performance Enhancements
- Add batch processing capabilities
- Implement worker pools for parallel processing
- Add connection pooling and request optimization
- Implement basic caching mechanism

### Phase 3: Message Queue Integration
- Set up message consumer for document chunks
- Implement publisher for completed embeddings
- Add error handling and retry logic
- Support dead letter queues for failed requests

### Phase 4: Advanced Optimizations
- Implement sophisticated caching with persistence
- Add adaptive batch sizing based on load
- Implement priority-based processing
- Add detailed metrics and monitoring

### Phase 5: Scaling Capabilities
- Refine stateless design for horizontal scaling
- Implement resource optimization for different workloads
- Add support for distributed caching
- Implement auto-scaling capabilities

## Testing Strategies

1. **Unit Tests**
   - Test embedding generation logic
   - Test provider selection and fallback
   - Test caching mechanisms
   - Test batch processing optimization

2. **Integration Tests**
   - Test OpenAI API integration
   - Test Ollama integration
   - Test LiteLLM proxy integration
   - Test message queue integration

3. **Performance Tests**
   - Measure embedding generation throughput
   - Test scaling capabilities under load
   - Measure batch processing efficiency
   - Test cache hit ratios and performance impact

4. **Reliability Tests**
   - Test provider fallback scenarios
   - Test error handling and recovery
   - Test message retry mechanisms
   - Test service resilience during provider outages

## Technology Stack

- FastAPI for API endpoints
- asyncio for asynchronous processing
- Redis for message queue and caching
- Prometheus for metrics collection
- OpenAI API client for embeddings
- Ollama client for local embeddings
- LiteLLM for model routing

## Configuration Options

```yaml
embedding_service:
  # Provider configuration
  providers:
    openai:
      enabled: true
      api_key: "${OPENAI_API_KEY}"
      default_model: "text-embedding-3-large"
      timeout_seconds: 30
      retries: 3
    
    ollama:
      enabled: true
      api_base: "http://ollama:11434"
      default_model: "mxbai-embed-large"
      timeout_seconds: 10
      retries: 3
  
  # Default provider selection
  default_provider: "openai"  # or "ollama"
  
  # Fallback configuration
  fallback:
    enabled: true
    strategy: "sequential"  # or "parallel"
    max_attempts: 2
  
  # Performance settings
  performance:
    batch_size: 32
    max_parallel_requests: 8
    queue_limit: 1000
    request_timeout_seconds: 60
  
  # Caching configuration
  cache:
    enabled: true
    backend: "redis"  # or "memory", "disk"
    ttl_seconds: 86400  # 24 hours
    max_size_mb: 1024
    redis_url: "redis://redis:6379/0"
  
  # Message queue configuration
  message_queue:
    consumer:
      topic: "document.chunks"
      group_id: "embedding-service"
      auto_offset_reset: "earliest"
    
    producer:
      topic: "embeddings.complete"
      compression: "gzip"
      batch_size: 16
```

## Dependencies

- OpenAI API Client
- LangChain Embeddings
- LiteLLM Client
- Redis Client
- FastAPI and Uvicorn
- Prometheus Client
- Message Queue Client (Redis, RabbitMQ, etc.)
- Caching Library

## Related Documents
- [Architecture Diagram](/workspaces/obelisk/vault/chatbot/architecture.md)
- [RAG Implementation Status](/workspaces/obelisk/vault/chatbot/rag/implementation-status.md)
- [Current Embedding Service](/workspaces/obelisk/obelisk/rag/embedding.py)
- [OpenAI Integration](/workspaces/obelisk/vault/chatbot/rag/openai/integration.md)
